"""
Collection of plotting templates
for data generated by abaqusPy examples.
"""
import os
path_site_packages='/home/younguj/anaconda2/lib/python2.7/site-packages/'
os.sys.path.append(path_site_packages)

# check if xwindow is available
from MP.lib import checkX
if checkX.main()!=0:
    import matplotlib as mpl
    mpl.use('Agg')

import numpy as np
import matplotlib.pyplot as plt
import MP.lib.mpl_lib

def strstr(fn=None,ref_dat=None,label=None,fig=None,**kwargs):
    """
    Arguments
    ---------
    fn
    ref_dat
    label
    fig
    **kwargs

    Returns
    -------
    fig
    """
    dat=np.loadtxt(fn).T

    if type(fig)==type(None):
        fig = plt.figure(figsize=(7,3))
        ax  = fig.add_subplot(121)
    elif len(fig.axes)!=1:
        raise SyntaxError, 'Expected a single axis'
    else:
        ax=fig.axes[0]

    if type(label)==type(None):
        label='Abaqus one element test'

    ax.plot(dat[0],dat[1]*1e-6,label=label,**kwargs)

    if type(ref_dat)!=type(None):
        ax.plot(ref_dat[0],ref_dat[1]*1e-6,label='Ref Data')

    ax.set_xlabel(r'$E_{11}$')
    ax.set_ylabel(r'$S_{11}$ [MPa]')
    ax.legend(fontsize=6,loc='best',bbox_to_anchor=(1,1))

    MP.lib.mpl_lib.ticks_bins(ax,axis='x',n=4)
    MP.lib.mpl_lib.ticks_bins(ax,axis='y',n=4)

    return fig
