"""
Collection of plotting templates
for data generated by abaqusPy examples.
"""

# check if xwindow is available
from MP.lib import checkX
if checkX.main()!=0:
    import matplotlib as mpl
    mpl.use('Agg')

import numpy as np
import matplotlib.pyplot as plt

def strstr(fn=None,ref_dat=None):
    """
    Argument
    --------
    fn
    ref_dat
    """
    dat=np.loadtxt(fn).T

    fig=plt.figure(figsize=(3.5,3))
    ax=fig.add_subplot(111)
    ax.plot(dat[0],dat[1]*1e-6,label='Abaqus one element')

    if type(ref_dat)!=type(None):
        ax.plot(ref_dat[0],ref_dat[1]*1e-6,label='Ref Data')

    ax.set_xlabel(r'$E_{11}$')
    ax.set_ylabel(r'$S_{11}$ [MPa]')
    ax.legend(fontsize=8)
    fnFig='%s.pdf'%fn.split('.')[0]
    fig.tight_layout()
    fig.savefig(fnFig,bbox_to_inches='tight')
    print 'Flow stress curve from %s saved to %s'%(fn,fnFig)
